import { useEffect, useState } from "react"
import Head from "next/head"

import { useRouter } from "next/router"

import { colors } from "@styles/theme"

import { loginWithGitHub, onAuthStateChanged } from "@/firebase/client"

import AppLayout from "@components/AppLayout"
import Avatar from "@components/Avatar"
import Button from "@components/Button"
import GitHub from "@components/icons/GitHub"
import Logo from "@components/icons/Logo"
import Loader from "@components/Loader"

export default function Home() {
  const [user, setUser] = useState(undefined)
  const router = useRouter()

  useEffect(() => {
    onAuthStateChanged((user) => setUser(user))
  }, [])

  useEffect(() => {
    user && router.replace("/home")
  }, [user])

  const handleClick = () => {
    loginWithGitHub()
      .then((user) => {
        setUser(user)
      })
      .catch((err) => {
        console.log(err)
      })
  }

  return (
    <>
      <Head>
        <title>Devter 🐦️</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <section>
          <Logo />
          <h1>Devter</h1>
          <h2>Talk about development with developers 👩‍💻️👨‍💻️</h2>
          <div>
            {user === null && (
              <Button onClick={handleClick}>
                <GitHub fill="#fff" width={24} height={24} />
                Login with GitHub
              </Button>
            )}
            {user === undefined && <Loader />}
          </div>
        </section>
      </AppLayout>

      <style jsx>
        {`
          section {
            display: grid;
            height: 100%;
            place-items: center;
            place-content: center;
          }

          div {
            margin-top: 16px;
          }

          h1 {
            color: ${colors.primary};
            font-weight: 800;
            margin-bottom: 16px;
          }

          h2 {
            color: ${colors.secondary};
            font-size: 21px;
            margin: 0;
          }
        `}
      </style>
    </>
  )
}
