import Head from "next/head";
import AppLayout from "@/components/AppLayout";
import Image from "next/image";
import {colors} from "@/styles/theme";
import Button from "@/components/Button";
import GitHub from "@/components/icons/GitHub";

export default function Home() {


  return (
    <>
      <Head>
        <title>Devter 🐦️</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <AppLayout>
        <section>
          <Image src='/luisjo-dev.svg' alt='Logo' title="" width={120} height={50}/>
          <h1>
            Devter
          </h1>
          <h2>
            Talk about development with developers 👩‍💻️👨‍💻️
          </h2>
          <div>
            <Button>
              <GitHub fill="#fff" width={24} height={24}/>
              Login with GitHub
            </Button>
          </div>

        </section>
      </AppLayout>

      <style jsx>{`
          section {
              display: grid;
              height: 100%;
              place-items: center;
              place-content: center;
          }

          div {
              margin-top: 16px;
          }

          h1 {
              color: ${colors.primary};
              font-weight: 800;
              margin-bottom: 16px;
          }

          h2 {
              color: ${colors.secondary};
              font-size: 21px;
              margin: 0;
          }
      `}
      </style>
    </>
  );
}
